### ISSUE TITLE
link to usage example is dead

### ISSUE THREAD

**Issue by Theadd** [mch1307/rancher-traefik#1]
Link to [usage example](https://goo.gl/zns1Ac) from `README.md` is dead.
```http
HTTP/1.1 301 Moved Permanently
```

**Comment by mch1307** [comment]
Hi,
Should be fixed now, sorry for that ;)

**Comment by Theadd** [comment]
Thank you.

You should take a look in that image resizing script that you are using there, it's reporting an incorrect value as `Content-Length` HTTP header resulting in some bizarre loading behavior in some images. Either not loading them or only part of it.

```diff
- Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
```

**Comment by mch1307** [comment]
Thanks for the info, was struggling with too many reverse proxies ;)
I have permanently moved the site somewhere else and updated the readme. Should be ok now.
I also updated to Traefik v1.3.5 ;)

**Comment by lucasctd** [comment]
It's down again :/

**Comment by mch1307** [comment]
fixed
